### ISSUE TITLE
Select all art boards

### ISSUE THREAD

**Issue by ghost** [bomberstudios/sketch-commands#16]
Create a command that will select all art boards in a page for the purpose of re-alining with the grid tool.
- Would be nice if the function could collapse all art boards as well.

**Comment by Clairepao** [comment]
+1

**Comment by andreasmb** [comment]
+1 (and hi @jcsizmadi! - cool running into you here)

**Comment by bomberstudios** [comment]
Are you all aware that this issue was closed more than a year ago, and the command is been there since then? https://github.com/bomberstudios/sketch-commands/blob/master/Select/All%20Artboards%20in%20Page.sketchplugin

**Comment by kevinSuttle** [comment]
@bomberstudios Link is broken.

**Comment by bomberstudios** [comment]
@kevinSuttle: https://github.com/bomberstudios/sketch-commands/blob/master/Sketch%20Commands.sketchplugin/Contents/Sketch/Select/All%20Artboards%20in%20Page.cocoascript
