### ISSUE TITLE
Unlock all locked layers

### ISSUE THREAD

**Issue by chengzd** [bomberstudios/sketch-commands#35]
Sometimes, locked layers are in nested groups, which are so hard to find.

Can I request this feature here?

**Comment by northswiss** [comment]
Any update on this? When dealing with huge docs, where some nested layers are locked it is very tedious to try and unlock. Something like "Layers > Unlock All"?

**Comment by andwiik** [comment]
Unlock all would be great!

**Comment by sconstantinides** [comment]
It's been awhile, but we just created a plugin for it:

Blog post: https://medium.com/truth-labs/sketch-plugin-unlock-all-layers-1ff9252f0689
Repo: https://github.com/truthlabs/sketch-unlock-all-layers

**Comment by bomberstudios** [comment]
Hey, that's an awesome plugin! The Unlock Hover things is specially clever : )

I've added your plugin to https://github.com/sketchplugins/plugin-directory, so I'll just go ahead and close this issue : )
