### ISSUE TITLE
Export page

### ISSUE THREAD

**Issue by staticdreams** [bomberstudios/sketch-commands#38]
Hi. I'm sorry if this has been asked before, but is it possible to export all the artboards in the current page as a single file, the way they are presented on the screen?

Say, when I want to show all the artboard on a single page to a client. Is it possible at all?

**Comment by rizwanjavaid** [comment]
+1 Having this feature would greatly speed up my workflow.

**Comment by igo903** [comment]
+1 @bomberstudios  any update for this feature? It would be a great feature for most users. Thanks.

**Comment by bomberstudios** [comment]
Apologies for taking so long to do this! Life happened : )

Merry Xmas!
