### ISSUE TITLE
Change default shortcut to move an object 100px

### ISSUE THREAD

**Issue by xavez** [bomberstudios/sketch-commands#54]
The `option+shift+arrow` default shortcut interferes with the OS-level text-selection shortcut. `option+shift+arrow[left/right]` selects the word to the right or left of the cursor. I use this a lot when renaming layers and artboards.

The default Sketch Commands shortcut interferes with this and it’s pretty annoying. I can imagine other people have this problem too.

**Comment by Ma11k** [comment]
> The option+shift+arrow default shortcut interferes with the OS-level text-selection shortcut. option+shift+arrow[left/right] selects the word to the right or left of the cursor. I use this a lot when renaming layers and artboards.
> 
> The default Sketch Commands shortcut interferes with this and it’s pretty annoying. I can imagine other people have this problem too.

Yes, I confirm, I have that problem too, but I've got used to it already :-)


-- 
Mikhail Miroshnikov

**Comment by bomberstudios** [comment]
You are completely right, thanks for the reminder. Let's fix this : )

**Comment by ricburton** [comment]
Apologies, guys. I use the shortcut so often I didn’t realise this for a while. @bomberstudios, have the guys had a chance to add an "isEditing" flag or something to that effect for text and shapes?

**Comment by ricburton** [comment]
@bomberstudios any way I can fix this? :)
