### ISSUE TITLE
All Artboards In Page leaves artboards in other pages selected

### ISSUE THREAD

**Issue by pkvdesigns** [bomberstudios/sketch-commands#56]
The current plugin for All Artboards In Page does deselect everthing in the current page before selecting all artboards. However it keeps the selected layers in other Pages in the same document.

I use the plugin to select all artboards in this page for exporting to a particular folder for the page.

Thanks in advance ;)

**Comment by bomberstudios** [comment]
I'm not sure I'm understanding what the request is here?

**Comment by pkvdesigns** [comment]
Hi I made a short screencast to demo the problem: http://quick.as/X6ZBupGDz

hope it helps ;)

**Comment by bomberstudios** [comment]
Crystal clear now! Thanks : )

I'll see what I can do : )

**Comment by pkvdesigns** [comment]
Awesome thanks!
