### ISSUE TITLE
Update project structure to follow new Sketch plugin guidelines

### ISSUE THREAD

**Issue by guerrero** [bomberstudios/sketch-commands#60]
Inspired by this repo, I'm creating my own commands and most of them have been borrowed from yours so, if you're interested, I can create a PR to update this repo structure. Some of these changes would be:
- Replace `.jstalk` by `.cocoascript`
- Create a `.sketchplugin` folder
- Add a `manifest.json` file
- Add a nodeJS task to update `manifest.json` when new files are added or updated into the sketch plugin folder

**Comment by bomberstudios** [comment]
That sounds awesome, and it's something I'd do myself if I had the time, so I'll happily merge a pull request with these changes from you : )

**Comment by guerrero** [comment]
Done :) #61

**Comment by bomberstudios** [comment]
Awesome! Will review and merge in a minute : )

**Comment by guerrero** [comment]
@bomberstudios Great! Thanks for your support, also I've seen some other changes that can be done to improve the repo and save some lines of code. Some of them are the following:

- Delete sandbox file and modify files that uses sandbox methods
- Remove semicolons due they are [unnecesary in CocoaScript](developer.sketchapp.com/introduction/cocoascript/other-cocoascript-syntax-notes)
- Add two tasks, one to [update manifest](https://github.com/guerrero/sketch-commands/blob/master/tasks/manifest-update-folders.js) and the other one to copy this repo into your sketch plugins folder and update it when files are changed to improve development and testing

I've also other recommendations and propositions, like use dot notation to support linting tools, but I don't know if you're interested and I don't want to be like a spammer opening a lot of issues at the same time so, if you wish, I can proceed creating some issues.

Thanks!

**Comment by bomberstudios** [comment]
> Delete sandbox file and modify files that uses sandbox methods

Just did this locally, so I'll take it and will push in a minute.

The rest look reasonable, and I'd love to get pull requests for them : )

**Comment by guerrero** [comment]
Nice! I'll create them in the next few days.

P.S. Thanks to mention me in your README's Thanks section!

**Comment by bomberstudios** [comment]
> P.S. Thanks to mention me in your README's Thanks section!

It's the least I could do!
