### ISSUE TITLE
"Export All Artboards as png in..." doesn't give a prompt

### ISSUE THREAD

**Issue by knynkwl** [bomberstudios/sketch-commands#64]
When using this tool, it doesn't seem to do anything. Same goes for "Export All Artboards as png"

The only ones that seem to work are "Selection to ..." and "Whole Page ..."

OSX El Capitan
V10.11.3

Sketch
V3.5.1 (25234)

**Comment by tbnv** [comment]
Hi,

Most commands don't work at all indeed. Here is a console error example:

```
3/03/16 18:52:07,825 All Artboards as PNG in… (Sketch Plugin)[2730]: ReferenceError: Can't find variable: context
line: 17
sourceURL: [plugins folder]/Sketch Commands.sketchplugin/Contents/Sketch/Export/All Artboards as PNG in….cocoascript
column: 22
```

**Comment by v3nt** [comment]
+1 - can't export anything with 3.6.1.

**Comment by kenrossi** [comment]
The export is completely broken with 3.5.2 as well

**Comment by tbnv** [comment]
Well… :(

**Comment by bomberstudios** [comment]
Sorry about that, I just pushed a change that (hopefully) fixes this issue : )

**Comment by tbnv** [comment]
Hi. Many thanks for the update. 😄
Unfortunately the plugin doesn't seem to respect the @x size set in the export options.

**Comment by bomberstudios** [comment]
I know. There's another issue open for that: #55

**Comment by tbnv** [comment]
Hi. Any news about a working `@2x` export or respecting the slice export options? :)
