### ISSUE TITLE
Duplicate Artboard no longer offsets the duplicated artboard in Sketch 40

### ISSUE THREAD

**Issue by stevebrown** [bomberstudios/sketch-commands#68]
The duplicate artboard routine broke with Sketch 40. The artboards are duplicated in place and not offset in the direction indicated by the command name.

**Comment by bomberstudios** [comment]
Ah, I had a bunch of fixes locally that I forgot to push :facepalm:

Will push them in a second : )

**Comment by bomberstudios** [comment]
Fixed in 4bcb4e6f952ee0a5c56cac3372c50cab04126011
