### ISSUE TITLE
Export Page to PDF / PNG no longer works

### ISSUE THREAD

**Issue by adambryce** [bomberstudios/sketch-commands#71]
Love this function and can't find it in any other plugin! 

Appears it has stopped working since the update. 

Console is as follows:

11/13/16 9:30:04.247 AM Whole Page to Desktop as PDF (Sketch Plugin)[66227]: TypeError: doc.currentView().totalRectForLayers is not a function. (In 'doc.currentView().totalRectForLayers(all)', 'doc.currentView().totalRectForLayers' is undefined)
line: 4
sourceURL: /Users/adamxx/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Sketch Commands.sketchplugin/Contents/Sketch/Export/Whole Page to Desktop as PDF.cocoascript
column: 50

**Comment by andrewharwood-rev** [comment]
Great feature.  Sad that my is also broken.  Console reads same error message.

**Comment by toorshia** [comment]
+1. What happened? :)

**Comment by andrewharwood-rev** [comment]
In short, nothing happens.  

Steps to reproduce:
1. Navigate to Plugins > Sketch Commands > Export > Whole Page to Desktop as PNG

Expected Behavior:
1. Page is exported as .PNG and saved to desktop.

Actual Behavior:
1. The file isn't exported.  No error message is given.

I hope that helps.

**Comment by kgowda** [comment]
Yep. Does not seem to be working. :/

**Comment by pkvdesigns** [comment]
+1, use all artboards to PNG all the time.. Hope it can be fixed!

**Comment by bre7** [comment]
Possible solution sent. Check #75
