### ISSUE TITLE
Update README to include command information

### ISSUE THREAD

**Issue by joeyfigaro** [bomberstudios/sketch-commands#74]
...alternatively, get [orangecommands.com](http://orangecommands.com) back up. I didn't use Fireworks, so I don't know what this plugin offers.

**Comment by bomberstudios** [comment]
There's a link to Orange Commands's GitHub repo on the README, where all the documentation for the Fireworks commands can be found.

I'll move that documentation to this project, rather than resurrecting a dead site : )

**Comment by joeyfigaro** [comment]
@bomberstudios Holy late reply on my part. Thank you! Closing this guy.
