### ISSUE TITLE
Select Current Artboard broken

### ISSUE THREAD

**Issue by peternowell** [bomberstudios/sketch-commands#77]
Hey @bomberstudios, the Select > Current Artboard command has long been one of my most frequently-used features in Sketch. It appears to be broken in recent versions of Sketch however. Would this be easy to fix? It's silly how much I rely on that command... probably once every 2 minutes that I use Sketch.

**Comment by bomberstudios** [comment]
Fixed, thanks for the report! : )

**Comment by peternowell** [comment]
Wow! Thanks for taking care of that so quickly, Ale! 🙏🏼
