### ISSUE TITLE
Text layer within group unclickable after moving 100px (Sketch 52.5)

### ISSUE THREAD

**Issue by derekatkinson** [bomberstudios/sketch-commands#80]
**Summary:**
When a text layer within a group is moved, the group remains in the same place and the text layer becomes unclickable on the canvas.

**Steps to Reproduce:**
1. Create a text layer
2. Create a group from the text layer
3. Select the text layer within the group
4. Move the text layer 100px using the menu item in Sketch Commands plugin
5. Try clicking on the text layer

**Expected Results**
Text layer should be clickable on the canvas, exactly as it is after using Sketch's built in 1px and 10px movement shortcuts.

**Actual Results:**
Text layer is not clickable on the canvas.

**Additional Information:**

- Sketch version: 52.5
- macOS version: 10.14.2

**Comment by bomberstudios** [comment]
Should be fixed in v3.6.3
