### ISSUE TITLE
Space Vertical & Space Horizontal Spacing field isn't keyboard focusable (Sketch 53)

### ISSUE THREAD

**Issue by perpetualgrimace** [bomberstudios/sketch-commands#81]
Since Sketch v53, when I run the `Space Vertical` or `Space Horizontal` commands, the `Spacing` input field isn't focused by default, and won't get focus if I try and shift tab back to it. Keyboard focus cycles only between the `Cancel` and `OK` buttons.

The field can of course still be clicked and then edited. But that slows me down considerably.

I never realize how much I rely on plugins until the team updates Sketch and breaks a command or two. 😭

**Comment by bomberstudios** [comment]
Sorry about this, and apologies for the very late reply. I'll push an update that fixes this in a bit

**Comment by perpetualgrimace** [comment]
Thank you! 🙏

**Comment by perpetualgrimace** [comment]
I was wondering why this didn't seem to have been fixed...turns out I was using a different set of commands from the sketch commands plugin. Remapped my keyboard shortcuts to this one and it works. 😅

Thanks again for the fix!
