### ISSUE TITLE
Sketch Commands causing severe performance issues and crash to desktop

### ISSUE THREAD

**Issue by marcushasfun** [bomberstudios/sketch-commands#82]
[Sketch Crash Log.txt](https://github.com/bomberstudios/sketch-commands/files/5258094/Sketch.Crash.Log.txt)

**Comment by bomberstudios** [comment]
I've checked the crash log and there's a few possible causes for it.

Would you mind sharing more details of what you were doing when this happened? A sample document and a list of steps to reproduce would be ideal.

Thanks in advance!
